FROM docker.io/centos/postgresql-12-centos7

USER root

# Adds the semver extension on top of the official image
RUN yum install --assumeyes epel-release && \
    yum install --assumeyes gcc make rh-postgresql12-postgresql-devel wget which && \
    yum clean all

ENV PG_SEMVER_VERSION=0.32.0
ENV PG_CONFIG=/opt/rh/rh-postgresql12/root/usr/bin/pg_config
RUN cd /tmp/ && \
    wget https://github.com/theory/pg-semver/archive/refs/tags/v${PG_SEMVER_VERSION}.tar.gz && \
    tar xvf v${PG_SEMVER_VERSION}.tar.gz && \
    cd pg-semver-${PG_SEMVER_VERSION}/ && \
    make && \
    make install

# Run the container as user postgres
USER 26
