#!/usr/bin/python
import logging
import os
import pyfaf

if __name__ == "__main__":
    cmdline_parser = pyfaf.argparse.ArgumentParser()
    cmdline_parser.parse_args()

    lobdir = pyfaf.config.CONFIG["storage.lobdir"]
    for obj in os.listdir(lobdir):
        logging.info("Processing object {0}".format(obj))
        objdir = os.path.join(lobdir, obj)
        for lobname in os.listdir(objdir):
            logging.info("Processing LOB {0}".format(lobname))
            lobnamedir = os.path.join(objdir, lobname)
            for pk in os.listdir(lobnamedir):
                pkpath = os.path.join(lobnamedir, pk)
                if not os.path.isfile(pkpath):
                    logging.debug("Skipping {0} - not a regular file".format(pkpath))
                    continue

                if len(pk) < 5:
                    pk_long = "{0}{1}".format("".join("0" for i in xrange(5 - len(pk))), pk)
                else:
                    pk_long = pk

                newdir = os.path.join(lobnamedir, pk_long[0:2], pk_long[2:4])
                if not os.path.isdir(newdir):
                    logging.debug("mkdir {0}".format(newdir))
                    os.makedirs(newdir)

                newpath = os.path.join(newdir, pk)
                logging.debug("mv {0} {1}".format(pkpath, newpath))
                os.rename(pkpath, newpath)
