#! /usr/bin/python
import cgi
import subprocess
import sys
import os

# form for bug_id imports
print 'Content-type: text/html\n\n'
print '<title>Backtrace analyzing page</title>'
print '<body>'
print '<form action="http://localhost/cgi-bin/analyze.py" method="get">'
print 'Bug ID: <input type="text" name="bug_id">  <br />'
print '<input type="submit" value="Submit" />'
print '</form>'

form = cgi.FieldStorage()
bug_id = form.getvalue('bug_id')

# we got our bug_id so let's call bt_comparison script to get similar backtraces
if bug_id:
    bt_comparison_proc = subprocess.Popen(['faf-btserver-distance', bug_id, '-v'],
                                          stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    stdout, stderr = bt_comparison_proc.communicate()
    if bt_comparison_proc.returncode == 2:
        print '<h3>No backtrace file found for given bug id.<h3>'
    elif bt_comparison_proc.returncode == 3:
        print '<h3>No component found for given bug id.<h3>'
    else:
        print '<h3>Bugs with similar backtrace as bug #' + bug_id + ':</h3>'
        print '<p>' + stdout + '</p>'
        print stderr

print '</body>'
