#!/usr/bin/python
# Copyright (C) 2012 Red Hat, Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
import os
import pyfaf
import btparser
import logging

# Command line argument processing
cmdline_parser = pyfaf.argparse.ArgumentParser()
cmdline_parser.add_argument("--optimize", action="store_true", default=False, help="Optimize threads before analysis")
cmdline_parser.add_argument("--raw", action="store_true", default=False, help="Don't normalize threads before analysis")
cmdline_args = cmdline_parser.parse_args()

db = pyfaf.cache.Database()
db.execute("SELECT id FROM rhbz_bug WHERE whiteboard LIKE '%%abrt_hash:%%'")

stats = dict()

rows = db.fetchall()
for (i, row) in enumerate(rows):
    logging.info("[{0}/{1}] Processing {2}".format(i + 1, len(rows), row[0]))

    # Parse the backtrace
    try:
        backtrace = pyfaf.btserver.get_backtrace(row[0])
        if cmdline_args.optimize:
            thread = pyfaf.btserver.get_optimized_thread(backtrace)
        else:
            thread = pyfaf.btserver.get_crash_thread(backtrace, normalize=not cmdline_args.raw, setlibs=False)
    except:
        logging.debug("Unable to parse the backtrace, skipping")
        continue

    for frame in thread.frames:
        name = frame.get_function_name()
        if name == "??":
            continue
        source = frame.get_source_file()
        if name not in stats:
            stats[name] = [0, set()]
        stats[name][0] += 1
        source_set = stats[name][1]
        if isinstance(source_set, set):
            source_set.add(source)
            # Give up on tracking sources if there are more than 20
            if len(source_set) > 20:
                stats[name][1] = None

db.close()

stats = list(stats.iteritems())
stats.sort(key=lambda stat: stat[1][0], reverse=True)

logging.info("Printing stats")

for stat in stats:
    print stat[1][0], stat[0], "\t\t",
    if stat[1][1] != None:
        print list(stat[1][1])
    else:
        print "[...]"
