#!/usr/bin/env python
import os

from django.core.management import call_command

from pyfaf import config, storage
from pyfaf.storage import fixtures

DBFILE = '/tmp/faf_test.db'

def main():
    try:
        os.unlink(DBFILE)
    except OSError:
        print 'Unable to delete old database: "%s"' % DBFILE
        pass
    cstring = 'sqlite:///%s' % DBFILE
    config.CONFIG['storage.connectstring'] = cstring

    # call syncdb
    os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'pyfaf.hub.settings')
    call_command('syncdb', interactive=False)

    db = storage.getDatabase()
    meta = storage.GenericTable.metadata
    gen = fixtures.Generator(db, meta)
    gen.run()

if __name__ == '__main__':
    main()
