#!/usr/bin/python
# Copyright (C) 2011 Red Hat, Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
import pyfaf
import sys
import subprocess
import logging
from pyfaf.storage import *

# Command line argument processing
cmdline_parser = pyfaf.argparse.ArgumentParser()
cmdline_args = cmdline_parser.parse_args()

db = pyfaf.storage.Database(debug=cmdline_args.verbose > 2)
opsys = db.session.query(OpSys).filter(OpSys.name == 'Fedora').one()

logging.info("Loading collection list from Fedora Package Database.")
args = ["faf-fedora-pkgdb", "collections"]
collection_list_text = pyfaf.run.process(args, stdout=subprocess.PIPE, timeout=30*60, timeout_attempts=1, returncode_attempts=2)[0]
collection_list = [line.strip() for line in collection_list_text.splitlines()]
logging.info("Found {0} collections in Fedora Package Database.".format(len(collection_list)))

logging.info("Removing old collections in storage.")
db.session.query(OpSysRelease).delete()

index = 0
for collection_id in collection_list:
    index += 1
    logging.info("[{0}/{1}] Processing collection #{2}.".format(index, len(collection_list), collection_id))
    args = ["faf-fedora-pkgdb", "collection", collection_id]
    pkgdb_proc = subprocess.Popen(args, stdout=subprocess.PIPE)
    collection_text = pkgdb_proc.communicate()[0]
    if pkgdb_proc.returncode != 0:
        sys.stderr.write("Failed to get collection #{0} from Fedora package database.\n".format(collection_id))
        exit(1)
    pyfaf.run.cache_add_text(collection_text, collection_id, "fedora-pkgdb-collection", overwrite=True)

    collection = pyfaf.run.cache_get("fedora-pkgdb-collection", collection_id)
    if collection.name != opsys.name:
        continue

    opsys_release = OpSysRelease()
    opsys_release.id = collection.id
    opsys_release.opsys = opsys
    opsys_release.version = collection.version
    db.session.add(opsys_release)

db.session.flush()
