#!/usr/bin/env python

import pyfaf
from pyfaf.storage import *

from  sqlalchemy.sql.expression import func

db = pyfaf.storage.getDatabase()
session = db.session

def first(obj):
    return session.query(obj).first()

def any(obj):
    return session.query(obj).order_by(func.random()).first()

try:
    import IPython
except ImportError:
    print('IPython required')

if hasattr(IPython, "embed"):
    IPython.embed()
else:
    IPython.Shell.IPShellEmbed()()
