#!/bin/bash

DEF_VER=1.3.1
LF='
'

if test -d .git -o -f .git &&
    VN=$(git describe --tags --match "[0-9]*" --abbrev=4 HEAD 2>/dev/null) &&
    case "$VN" in
    *$LF*) (exit 1) ;;
    [0-9]*)
        git update-index -q --refresh
    esac
then
    VN=$(echo "$VN" | sed -e 's/-/./' | sed -e 's/-/+/');
else
    VN="$DEF_VER"
fi

echo -n $VN > faf-version
