#!/usr/bin/python

import os
import sys
import unittest
#import StringIO
import xmlrpclib
import traceback
from datetime import datetime

sys.path.insert(0, os.path.abspath(".."))
os.environ["PATH"] = "{0}:{1}".format(os.path.abspath(".."), os.environ["PATH"])
import pyfaf
import xmlrpcrecorder

#
# This test uses stub object (XmlRpcPlayer) to act as an xmlrpclib proxy that
# returns predefined responses to predefined queries. Such an object is created
# by intercepting arguments and return values during actual communication over
# the network.
#
# Thus, if you need to update this test, you need to:
# 1) Set the variable 'record' to True.
# 2) Provide your bugzilla login and password in setUpClass method.
# 3) Run & update the test (the test runs against actual bugzilla now and the
#    traffic is recorded).
# 4) Set the variable 'record' to False. Erase your bugzilla credentials. Grep
#    recorded files to make sure they didn't end up there somehow.
# 5) See if the test still works.
#
# TODO
# - exception raising is not tested due to pickle bug (needs workaround)
# - search_bug() not tested as it is about to be rewritten
#

record = False
xmlrpcrecord_file = 'bugzilla_traffic'
httprecord_file = 'bugzilla_attachments'

class BugzillaTestCase(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.bz = pyfaf.bugzilla.Bugzilla('https://partner-bugzilla.redhat.com/xmlrpc.cgi')
        if record:
            cls.bz.login('bzlogin', 'bzpassword')
            cls.bz.proxy = xmlrpcrecorder.XmlRpcRecorder(cls.bz.proxy)
            cls.bz.opener = xmlrpcrecorder.OpenerRecorder(cls.bz.opener)
        else:
            cls.bz.proxy = xmlrpcrecorder.XmlRpcPlayer(xmlrpcrecord_file)
            cls.bz.opener = xmlrpcrecorder.OpenerPlayer(httprecord_file)

    @classmethod
    def tearDownClass(cls):
        if record:
            cls.bz.proxy.save_record(xmlrpcrecord_file)
            cls.bz.opener.save_record(httprecord_file)

    def setUp(self):
        self.bz = self.__class__.bz

    def tearDown(self):
        pass

    def test_user_id_from_login(self):
        ret = self.bz.user_id_from_login('mmilata@redhat.com')
        self.assertEqual(ret, 316147)

        # currently, python cannot reliably pickle exceptions and I'm too tired
        # to write a workaround: http://bugs.python.org/issue1692335
        #with self.assertRaisesRegexp(xmlrpclib.Fault, 'There is no user named'):
        #    ret = self.bz.user_id_from_login('unknownusername')

    def test_user_ids_from_logins(self):
        ids = self.bz.user_ids_from_logins(['mmilata@redhat.com', 'fedora-admin-xmlrpc@redhat.com'])
        self.assertEqual(ids, [316147, 271726])

        #with self.assertRaisesRegexp(xmlrpclib.Fault, 'There is no user named'):
        #    ids = self.bz.user_ids_from_logins(['mmilata@redhat.com', 'whothehellareyou'])

    def test_bug(self):
        res = self.bz.bug(677789, False, False, False) #no comments, no attachments

        self.assertEqual(len(res), 1)
        bug = res[0]

        self.assertEqual(bug.id, 677789)
        self.assertEqual(bug.status, 'CLOSED')
        self.assertEqual(bug.resolution, 'ERRATA')
        self.assertIsNone(bug.resolution_dup_id)
        self.assertEqual(bug.product, 'Red Hat Enterprise Linux 6')
        self.assertEqual(bug.product_version, '6.1')
        self.assertEqual(bug.attachments, [])
        self.assertEqual(bug.whiteboard, 'abrt_hash:36d6572a6d9f88437a85ce7fefa9968eedd36a4d')
        self.assertEqual(bug.cc, [303287, 290792, 265412, 5319, 165188])
        self.assertEqual(bug.component, 'dosfstools')
        self.assertEqual(bug.last_change_time, datetime(2011, 12, 6, 9, 56, 30))
        self.assertEqual(bug.creation_time, datetime(2011, 2, 15, 20, 51))
        self.assertEqual(bug.comments, [3539501, 3539504, 3539562, 3587288, 3879154, 3893843, 4193548])
        self.assertEqual(bug.summary, 'fsck.vfat hangs during checking of VFAT if there are chains of orphaned clusters')
        self.assertEqual(bug.creator_id, 290792)
        self.assertEqual(len(bug.history), 3)

        res = self.bz.bug(667100, False, True, True) #with comments and attachments

        self.assertEqual(len(res), 3)
        (bug, comments, attach) = res

        self.assertEqual(bug.id, 667100)
        self.assertEqual(bug.status, 'NEW')
        self.assertEqual(bug.product, 'Fedora')
        self.assertEqual(bug.product_version, 'rawhide')
        self.assertEqual(bug.attachments, [471656])
        self.assertIsNone(bug.whiteboard)
        self.assertEqual(bug.cc, [192952, 165199, 93466])
        self.assertEqual(bug.component, 'rpm')
        self.assertEqual(bug.last_change_time, datetime(2011, 1, 4, 13, 16, 45))
        self.assertEqual(bug.creation_time, datetime(2011, 1, 4, 12, 44))
        self.assertEqual(bug.comments, [3452584, 3452621, 3452631])
        self.assertEqual(bug.summary, 'rpm hang without any output')
        self.assertEqual(bug.creator_id, 282789)
        self.assertIsNone(bug.resolution_dup_id)
        self.assertIsNone(bug.resolution)
        self.assertEqual(bug.history, [])

        self.assertEqual(len(comments), 3)
        (_, c2, _) = comments

        self.assertEqual(c2.id, 3452621)
        self.assertEqual(c2.body, "I managed to get strace (I've extracted from RPM using rpm2cpio)")
        self.assertIsNone(c2.duplicate_id)
        self.assertEqual(c2.attachment_id, 471656)
        self.assertEqual(c2.number, 1)
        self.assertEqual(c2.bug_id, 667100)
        self.assertEqual(c2.time, datetime(2011, 1, 4, 8, 8, 2))
        self.assertEqual(c2.author_id, 282789)
        self.assertEqual(c2.type, 'NEW_ATTACHMENT')
        self.assertEqual(c2.is_private, False)

        self.assertEqual(len(attach), 1)
        a1 = attach[0]

        self.assertEqual(a1.user_id, 282789)
        self.assertEqual(a1.description, 'Strace output')
        self.assertEqual(len(a1.contents), 34597)
        self.assertEqual(a1.is_obsolete, False)
        self.assertEqual(a1.is_patch, False)
        self.assertEqual(a1.creation_time, datetime(2011, 1, 4, 8, 8))
        self.assertEqual(a1.last_change_time, datetime(2011, 1, 4, 8, 8, 2))
        self.assertEqual(a1.bug_id, 667100)
        self.assertEqual(a1.is_private, False)
        self.assertEqual(a1.file_name, 'rpm.out.txt')
        self.assertEqual(a1.is_url, False)
        self.assertEqual(a1.id, 471656)
        self.assertEqual(a1.mime_type, 'text/plain')

    open_bug_data = {
        'product': 'Fedora',
        'version': 'rawhide',
        'component': 'abrt',
        'summary': 'A test bug',
    }

    def open_bug(self):
        # add name of the caller to the description to allow XmlRpcPlayer
        # to have exactly one response for each query
        caller = traceback.extract_stack(limit=2)[0][2]
        self.open_bug_data['description'] = 'Bug created from pyfaf bugzilla unit test ({0}).'.format(caller)
        return self.bz.new_bug(raw = False, **self.open_bug_data)

    def test_new_bug(self):
        bugid = self.open_bug()
        res = self.bz.bug(bugid, False, False, False)

        self.assertEqual(len(res), 1)
        bug = res[0]

        self.assertEqual(bug.id, bugid)
        self.assertEqual(bug.product, self.open_bug_data['product'])
        self.assertEqual(bug.product_version, self.open_bug_data['version'])
        self.assertEqual(bug.component, self.open_bug_data['component'])
        self.assertEqual(bug.summary, self.open_bug_data['summary'])

# prints to stdout
#    def test_bug_fields(self):
#        buf = StringIO.StringIO()
#        sys.stdin = buf
#        self.bz.bug_fields()
#        sys.stdin = sys.__stdin__
#        #do something w/ buf.getvalue()

# prints to stdout, to be tested after rewrite
#    def test_search_bugs(self):
#        #def search_bugs(self, raw, whiteboard, whiteboard_type, order, chfield_from, chfield_to, chfield, product, product_version, output_format):
#        pass

    def test_comment(self):
        comment = self.bz.comment(3882602, raw=False)

        self.assertIsNone(comment.body)
        self.assertIsNone(comment.duplicate_id)
        self.assertIsNone(comment.attachment_id)
        self.assertIn('metatags', comment.text)
        self.assertEqual(comment.number, 0)
        self.assertEqual(comment.bug_id, 721178)
        self.assertEqual(comment.time, datetime(2011, 7, 13, 22, 55, 29))
        self.assertEqual(comment.author_id, 298454)
        self.assertEqual(comment.type, 'NORMAL')
        self.assertEqual(comment.id, 3882602)
        self.assertEqual(comment.is_private, False)

    def test_user(self):
        user = self.bz.user(316147, raw=False)

        self.assertEqual(user.id, 316147)
        self.assertEqual(user.can_login, True)
        self.assertEqual(user.real_name, 'Martin Milata')
        self.assertEqual(user.name, 'mmilata@redhat.com')
        self.assertEqual(user.email, 'mmilata@redhat.com')

    def test_attachment(self):
        attach = self.bz.attachment(477666, raw=False)

        self.assertEqual(attach.id, 477666)
        self.assertEqual(attach.user_id, 206660)
        self.assertEqual(attach.description, 'File: backtrace')
        self.assertEqual(attach.is_obsolete, False)
        self.assertEqual(attach.is_patch, False)
        self.assertEqual(attach.creation_time, datetime(2011, 2, 8, 18, 48, 0))
        self.assertEqual(attach.last_change_time, datetime(2011, 2, 8, 18, 48, 56))
        self.assertEqual(attach.bug_id, 676074)
        self.assertEqual(attach.is_private, False)
        self.assertEqual(attach.file_name, 'backtrace')
        self.assertEqual(attach.is_url, False)
        self.assertEqual(attach.mime_type, 'text/plain')
        self.assertIn('Segmentation fault', attach.contents)

    def test_add_comment(self):
        comment_text = "Comment added from pyfaf test_add_comment"
        bug_id = self.open_bug()
        comment_id = self.bz.add_comment(bug_id, comment_text)

        (bug, comments) = self.bz.bug(bug_id, False, True, False)

        self.assertEqual(len(comments), 2)
        c1 = comments[1]
        self.assertEqual(c1.body, comment_text)
        self.assertEqual(c1.id, comment_id)

    def test_close_as_duplicate(self):
        comment_text = "Bug closed from pyfaf test_close_as_duplicate"
        dupe_of = 679783

        bug_id = self.open_bug()
        self.bz.close_as_duplicate(bug_id, dupe_of, comment_text)

        (bug, comments) = self.bz.bug(bug_id, False, True, False)

        self.assertEqual(bug.status, 'CLOSED')
        self.assertEqual(bug.resolution, 'DUPLICATE')
        self.assertEqual(bug.resolution_dup_id, dupe_of)

        self.assertEqual(len(comments), 2)
        c1 = comments[1]
        self.assertEqual(c1.body, comment_text)
        self.assertEqual(c1.duplicate_id, dupe_of)

    def test_change_component(self):
        bug_id = self.open_bug()
        comment_text = "Changing component from pyfaf test_change_component"
        self.bz.change_component(bug_id, "libreport", comment_text)

        (bug, comments) = self.bz.bug(bug_id, False, True, False)

        self.assertEqual(bug.component, "libreport")
        self.assertEqual(len(comments), 2)
        c1 = comments[1]
        self.assertEqual(c1.body, comment_text)

if __name__ == '__main__':
    unittest.main()
