#!/usr/bin/python
# -*- encoding: utf-8 -*-
import json
import datetime

import unittest2 as unittest
import logging

import faftests

from pyfaf.bugtrackers import bugtrackers
from pyfaf.ureport import save, save_attachment, validate, validate_attachment

from pyfaf.storage.opsys import (Arch,
                                 OpSys,
                                 OpSysComponent,
                                 OpSysRelease,
                                 OpSysReleaseComponent)

from pyfaf.storage.report import Report
from pyfaf.storage.bugtracker import Bugtracker
from pyfaf.storage.bugzilla import BzBug, BzUser


class UreportTestCase(faftests.DatabaseCase):
    """
    Tests ureport processing functionality.
    """
    def setUp(self):
        """
        Add required stuff to the database
        """

        super(UreportTestCase, self).setUp()

        # add required data to database
        arch = Arch(name="x86_64")
        self.db.session.add(arch)

        noarch = Arch(name="noarch")
        self.db.session.add(noarch)

        sys = OpSys(name="Fedora")
        self.db.session.add(sys)

        rel = OpSysRelease(opsys=sys, version="18", status="ACTIVE")
        self.db.session.add(rel)

        rel20 = OpSysRelease(opsys=sys, version="20", status="ACTIVE")
        self.db.session.add(rel20)

        comp = OpSysComponent(opsys=sys, name="faf")
        self.db.session.add(comp)

        comp = OpSysComponent(opsys=sys, name="systemd")
        self.db.session.add(comp)

        comp = OpSysComponent(opsys=sys, name="kernel")
        self.db.session.add(comp)

        comp = OpSysComponent(opsys=sys, name="ibus-table")
        self.db.session.add(comp)

        comp = OpSysComponent(opsys=sys, name="eclipse")
        self.db.session.add(comp)

        rcomp = OpSysReleaseComponent(release=rel, component=comp)
        self.db.session.add(rcomp)

        tracker = Bugtracker(name="fedora-bugzilla")
        self.db.session.add(tracker)

        bzuser = BzUser(name="Fake user",
                        email="fake@example.org",
                        real_name="Fake name",
                        can_login=False)

        self.db.session.add(bzuser)

        bug = BzBug()
        bug.id = 123456
        bug.summary = "Fake bug"
        bug.status = "NEW"
        bug.creation_time = datetime.datetime.now()
        bug.last_change_time = datetime.datetime.now()
        bug.whiteboard = "empty"
        bug.tracker = tracker
        bug.creator = bzuser
        bug.component = comp
        bug.opsysrelease = rel

        self.bug = bug
        self.db.session.add(bug)
        self.db.session.flush()

        self.sample_report_names = ('ureport1', 'ureport2', 'ureport_core',
            'ureport_python', 'ureport_kerneloops', 'ureport_java')
        self.sample_reports = {}

        for report_name in self.sample_report_names:
            with open("sample_reports/{0}".format(report_name), "r") as file:
                self.sample_reports[report_name]= json.load(file)

        with open("sample_reports/bugzilla_attachment", "r") as file:
            self.bugzilla_attachment = json.load(file)

    def test_ureport_validation(self):
        """
        Check if ureport validation works correctly
        for both versions.
        """

        # validate raises FafError on failure
        for report_name in self.sample_report_names:
            validate(self.sample_reports[report_name])

    def test_ureport_saving(self):
        """
        Check if ureport saving works correctly.
        """

        # save raises FafError on failure
        for report_name in self.sample_report_names:            
            save(self.db, self.sample_reports[report_name])

    def test_attachment_validation(self):
        """
        Check if attachment validation works correctly.
        """

        validate_attachment(self.bugzilla_attachment)

    def test_attachment_saving(self):
        """
        Check if bugzilla attachment is added to report.
        """

        save(self.db, self.sample_reports['ureport2'])
        report = self.db.session.query(Report).first()

        # update hash locally
        reporthash = report.hashes[0].hash
        bz_attachment = self.bugzilla_attachment
        bz_attachment["bthash"] = reporthash

        class MockBugtracker(object):
            def download_bug_to_storage(db, bug_id):
                return self.bug

        bugtrackers["fedora-bugzilla"] = MockBugtracker()

        save_attachment(self.db, bz_attachment)
        self.assertEqual(len(report.bz_bugs), 1)

if __name__ == "__main__":
    logging.basicConfig(level=logging.DEBUG)
    unittest.main()
