#!/usr/bin/python
#
# This is FAF GCC wrapper
#

import os
import fakeargs
import sys
from subprocess import *

if __name__ == "__main__":
    args = fakeargs.FakeArgs(sys.argv)
    if os.getenv("FAF_LLVM_BUILD") is None:
        args.use_binary("/usr/bin/.gcc")
        sys.exit(call(args))

    args.use_binary("/usr/bin/clang")
    args.add_unique("-emit-llvm")
    args.remove_all("-Wall")

    retcode = call(args)
    if retcode:
        sys.exit(retcode)
