#!/bin/bash

mkdir -p /var/spool/faf/reports/incoming /var/spool/faf/reports/saved /var/spool/faf/reports/deferred /var/spool/faf/lob /var/spool/faf/attachments/incoming
chmod 755 /var/spool/faf

createdb
if [ $? == 0 ]
then
    psql -c "CREATE EXTENSION semver"
    faf-migrate-db --create-all
    faf-migrate-db --stamp-only
    faf init
    faf pull-releases -o fedora
else
    faf-migrate-db
fi
/usr/sbin/uwsgi --ini /etc/uwsgi.ini &
apachectl -DFOREGROUND
