#!/bin/bash

if [ ! -f /etc/faf/db.created ]
then
    mkdir -p /var/lib/postgres/data
    chown postgres:postgres /var/lib/postgres/data

    mkdir -p /var/spool/faf/reports/incoming /var/spool/faf/reports/saved /var/spool/faf/reports/deferred /var/spool/faf/lob /var/spool/faf/attachments/incoming
    chown -R faf:faf /var/spool/faf/reports
    chown -R faf:faf /var/spool/faf/lob
    chown -R faf:faf /var/spool/faf/attachments

    sudo -u postgres /usr/bin/pg_ctl initdb -D /var/lib/postgres/data > /dev/null
    sudo -u postgres /usr/bin/pg_ctl start -D /var/lib/postgres/data -w > /dev/null

    sudo -u postgres psql -c "CREATE USER faf;"
    sudo -u postgres psql -c "CREATE DATABASE faf;"
    sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE faf TO faf;"
    sudo -u postgres psql -c "ALTER USER faf WITH superuser;"
    sudo -u faf psql -c "CREATE EXTENSION semver;"
    sudo -u faf faf-migrate-db --create-all
    sudo -u faf faf-migrate-db --stamp-only
    sudo -u faf faf init
    sudo -u faf faf pull-releases -o fedora
    touch /etc/faf/db.created
else
    sudo -u postgres /usr/bin/pg_ctl start -D /var/lib/postgres/data -w > /dev/null
    sudo -u faf faf-migrate-db
fi
crond
apachectl -DFOREGROUND
